Skip rendering the table if there are no updates to display
psampaz/go-mod-outdated pull request #46
Opened 2021-04-28 20:00 UTC by Deseao

In my usecase I'd like to only see output if there is an update to perform.
This change skips running the table rendering if the filtered modules is an empty slice.

2021-04-29 21:00 UTC, Anedumgottil commented
+1

2021-06-13 19:45 UTC, psampaz requested changes
Thank you for your PR!

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +				t.Errorf("Error should be nil, got %w", err)
```suggestion
				t.Errorf("Error should be nil, got %s", err)
```

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner.go
> +type Style string
```suggestion
type OutputStyle string
```

to make it more explicit

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +		t.Errorf("Failed to read input file: %w", err)
```suggestion
		t.Errorf("Failed to read input file: %s", err)
```

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +		t.Errorf("Error should be nil, got %w", err)
```suggestion
		t.Errorf("Error should be nil, got %s", err)
```

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +		t.Errorf("Wanted an EOF error, got %w", err)
```suggestion
		t.Errorf("Wanted an EOF error, got %s", err)
```

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +		t.Errorf("Error should be nil, got %w", err)
```suggestion
		t.Errorf("Error should be nil, got %s", err)
```

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +	var result bytes.Buffer
Can you please rename this to **out** so that it is consistent with the other tests?

2021-06-13 19:45 UTC, psampaz commented on internal/runner/runner_test.go
> +	err = runner.Run(in, &result, true, true, false, runner.StyleDefault)
```suggestion
	err = runner.Run(in, &result, true, false, false, runner.StyleDefault)
```

no_direct_updates does not have indirect dependencies with updates, so this is not needed

2021-06-16 19:10 UTC, psampaz commented
cool thanks!

2021-06-16 19:41 UTC, psampaz requested changes
Also please add the _nestif_ linter to the exclude list in https://github.com/psampaz/go-mod-outdated/blob/master/.golangci.yml#L45

2021-06-16 19:41 UTC, psampaz commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
The empty table currently clearly communicates the absence of updates. I think you should add in this PR a message "No updates found" in order to make it more user friendly.

2021-06-16 19:41 UTC, psampaz commented on internal/runner/runner_test.go
> +}
```suggestion
func TestRunNoUpdatesCase(t *testing.T) {
	inBytes, err := ioutil.ReadFile("testdata/no_direct_updates.json")
	if err != nil {
		t.Errorf("Failed to read input file: %s", err)
	}

	in := bytes.NewBuffer(inBytes)

	var out bytes.Buffer

	err = runner.Run(in, &out, true, false, false, runner.StyleDefault)
	if err != nil {
		t.Errorf("Error should be nil, got %s", err)
	}

	if out.Len() != 0 {
		t.Errorf("Wanted an empty output, got \n%q", out.String())
	}
}
```

just to fix wsl linter

2021-06-16 19:41 UTC, psampaz commented on internal/runner/runner.go
> +type OutputStyle string
Please add a comment here (I know it is annoying) to make the linter happy:)

2021-06-16 19:41 UTC, psampaz commented on internal/runner/runner.go
> +const (
Same here :)

2021-06-16 19:42 UTC, psampaz commented
These are the last changes and then we can merge it. Thanks again for your time!

2021-06-16 19:54 UTC, Deseao commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
My usecase specifically wants no output to ease detection in CI, so I don't want _any_ output when there are no modules to display. This also fits a common pattern of tooling like `go fmt` where "no news is good news".

2021-06-16 19:59 UTC, Deseao commented
> Also please add the _nestif_ linter to the exclude list in https://github.com/psampaz/go-mod-outdated/blob/master/.golangci.yml#L45

I've opened https://github.com/psampaz/go-mod-outdated/pull/50 for this

2021-06-16 22:02 UTC, psampaz commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
But why you depend on the text output (which i cannot guarantee that it would not change in the future) while there is a ci  option https://github.com/psampaz/go-mod-outdated#ci-pipelines (https://github.com/psampaz/go-mod-outdated/pull/9) ? I believe you just need to check the exit code. If it is 1 it means that there are outdated dependencies. If it is 0 it mean you are up to date.

Your description "In my usecase I'd like to only see output if there is an update to perform." was not clear and I didn't understand that we talking about ci here.  The problem is that satisfying your use case means that it might break the ci pipeline of someone else that depends on the empty table output. 

Noone should depend on human readable messages or output format to decide to break a pipeline or not. I understand that in practice you might have to do it if there are not alternernatives but for this tool the is an safe alternative and this is the ci option.

2021-06-16 22:25 UTC, Deseao commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
I understand that there is a ci flag, and I tried to use it at first. Unfortunately I can't recall why that wasn't a good enough signal, it was something to do with how I had Jenkins set up to try to publish the report after the build but only if there were dependencies to update.

Regardless of the CI context though, I do think no output on empty result is more standard. Look at what golangci-lint does for example. It doesn't say "Good job, all your files are lint free!"

2021-07-11 20:14 UTC, psampaz commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
Sorry for my late reply. 

Regardless of the CI context I agree. Let's finish and merge this. Please add the nestif linter to the disabled list in order to make the pipeline green.  

Also please note that I cannot guarantee that this will not change in the future, so please use the ci flag on ci pipelines.

2021-07-12 15:03 UTC, Deseao commented on internal/runner/runner.go
> +				if len(filteredModules) > 0 {
Oh I actually did remember my usecase: I wanted to run several make targets inside a dockerfile like `make lint test check-deps build` and didn't want the -ci flag exit code to trigger an overall failure of the image build and just checked for the presence of a file to determine if there were out of date dependencies.

Totally understandable that this side effect might change.
I'll update the linter soon and we can get this merged in.

2021-07-12 16:48 UTC, psampaz approved these changes
:+1:

2021-07-12 16:48 UTC, merged